# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U6WD5A-bvWqPlW8_Z1xZ9QG9DkF00Q_s
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Dashboard Poktan Pacitan", layout="wide")

# ===========================
# LOAD DATA
# ===========================
@st.cache_data
def load_data():
    df = pd.read_csv("poktan_clean.csv")
    df["tipe"] = df["nama_poktan"].apply(
        lambda x: "KWT" if "kwt" in str(x).lower() else "Poktan"
    )
    return df

df = load_data()

# ======================================================
# PARSER MULTI-POKTAN PER DESA
# nama_poktan bisa berisi banyak poktan dalam 1 sel
# dipisah oleh \n / , / ;
# ======================================================
def generate_poktan_list(df):
    poktan_dict = {}

    for _, row in df.iterrows():
        kec = str(row["kecamatan"]).strip()
        desa = str(row["desa"]).strip()
        poktan_raw = str(row["nama_poktan"]).strip()

        # pisahkan oleh baris baru, koma, atau titik koma
        for sep in ["\n", ",", ";"]:
            poktan_raw = poktan_raw.replace(sep, "|")

        poktan_split = [p.strip() for p in poktan_raw.split("|") if p.strip()]

        # inisialisasi kecamatan
        if kec not in poktan_dict:
            poktan_dict[kec] = {}

        # inisialisasi desa
        if desa not in poktan_dict[kec]:
            poktan_dict[kec][desa] = []

        # tambahkan poktan
        for p in poktan_split:
            if p not in poktan_dict[kec][desa]:
                poktan_dict[kec][desa].append(p)

    return poktan_dict

poktan_list = generate_poktan_list(df)
# ===========================
# SIDEBAR MENU
# ===========================
menu = st.sidebar.selectbox(
    "Pilih Menu Visualisasi",
    [
        "Dashboard Utama",
        "Poktan per Kecamatan",
        "Poktan per Desa",
        "Top Desa Teraktif",
        "KWT vs Poktan",
        "Detail Poktan",
        "Tabel Data"
    ]
)

st.sidebar.info("Dashboard Kelembagaan Pertanian — Sabda Tani 2025")
st.sidebar.write("Data dari poktan_clean.csv")


# ===========================
# HALAMAN – DASHBOARD UTAMA
# ===========================
if menu == "Dashboard Utama":
    st.title("📊 Dashboard Kelembagaan Poktan Kabupaten Pacitan")

    total_kec = df["kecamatan"].nunique()
    total_desa = df["desa"].nunique()
    total_poktan = sum(len(p_list) for kec in poktan_list.values() for p_list in kec.values())

    col1, col2, col3 = st.columns(3)
    col1.metric("Total Kecamatan", total_kec)
    col2.metric("Total Desa", total_desa)
    col3.metric("Total Poktan", total_poktan)

    # Grafik poktan per kecamatan
    per_kec = []
    for kec, desa_dict in poktan_list.items():
        count = sum(len(p) for p in desa_dict.values())
        per_kec.append([kec, count])

    per_kec_df = pd.DataFrame(per_kec, columns=["kecamatan", "jumlah_poktan"])

    fig = px.bar(
        per_kec_df,
        x="kecamatan",
        y="jumlah_poktan",
        text="jumlah_poktan",
        title="📌 Jumlah Poktan per Kecamatan"
    )

    st.plotly_chart(fig, use_container_width=True)


# ===========================
# HALAMAN – PER KECAMATAN
# ===========================
elif menu == "Poktan per Kecamatan":
    st.title("🏞️ Poktan per Kecamatan")

    kec_select = st.selectbox("Pilih Kecamatan", list(poktan_list.keys()))

    desa_counts = []
    for desa, poktans in poktan_list[kec_select].items():
        desa_counts.append([desa, len(poktans)])

    df_desa = pd.DataFrame(desa_counts, columns=["desa", "jumlah_poktan"])

    fig = px.bar(
        df_desa,
        x="desa",
        y="jumlah_poktan",
        text="jumlah_poktan",
        title=f"📌 Jumlah Poktan per Desa – {kec_select}"
    )

    st.plotly_chart(fig, use_container_width=True)
    st.dataframe(df_desa)

# ================================
# HALAMAN - PER DESA
# ================================
elif menu == "Poktan per Desa":
    st.title("🏘️ Poktan per Desa")

    kec_select = st.selectbox("Pilih Kecamatan", list(poktan_list.keys()))
    desa_select = st.selectbox("Pilih Desa", list(poktan_list[kec_select].keys()))

    poktan_in_desa = poktan_list[kec_select][desa_select]

    st.subheader(f"📋 Daftar Poktan di {desa_select}")
    st.write(poktan_in_desa)

    fig = px.bar(
        x=poktan_in_desa,
        y=[1] * len(poktan_in_desa),
        labels={"x": "Nama Poktan", "y": "Jumlah"},
        title=f"Jumlah Poktan di Desa {desa_select}",
    )
    st.plotly_chart(fig, use_container_width=True)
    
# ======================================================
# HALAMAN  — DETAIL POKTAN
# ======================================================
elif menu == "Detail Poktan":
    st.title("🔍 Detail Poktan")

    kec_select = st.selectbox("Pilih Kecamatan", list(poktan_list.keys()))
    desa_select = st.selectbox("Pilih Desa", list(poktan_list[kec_select].keys()))
    poktan_select = st.selectbox("Pilih Poktan", poktan_list[kec_select][desa_select])

    detail = df[
        (df["kecamatan"] == kec_select)
        & (df["desa"] == desa_select)
        & (df["nama_poktan"].str.contains(poktan_select, case=False, na=False))
    ]

    st.subheader(f"📌 Detail Poktan: {poktan_select}")
    st.dataframe(detail if not detail.empty else "Tidak ada detail tambahan dalam dataset.")
# ===========================
# HALAMAN – TOP DESA
# ===========================
elif menu == "Top Desa Teraktif":
    st.title("🔥 Top Desa dengan Poktan Terbanyak")

    per_desa = df.groupby(["kecamatan", "desa"]).size().reset_index(name="jumlah_poktan")
    top_desa = per_desa.sort_values("jumlah_poktan", ascending=False).head(15)

    fig = px.bar(top_desa, x="jumlah_poktan", y="desa",
                 orientation="h",
                 color="jumlah_poktan",
                 title="Top 15 Desa Paling Aktif")
    st.plotly_chart(fig, use_container_width=True)


# ===========================
# HALAMAN – KWT VS POKTAN
# ===========================
elif menu == "KWT vs Poktan":
    st.title("🌾 Komposisi KWT vs Poktan")

    counts = df["tipe"].value_counts().reset_index()
    counts.columns = ["tipe", "jumlah"]
    fig = px.pie(counts, names="tipe", values="jumlah")
    st.plotly_chart(fig, use_container_width=True)


# ===========================
# HALAMAN – TABEL DATA
# ===========================
elif menu == "Tabel Data":
    st.title("📋 Data Lengkap Kelompok Tani")
    st.dataframe(df)

