# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U6WD5A-bvWqPlW8_Z1xZ9QG9DkF00Q_s
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="SABDA TANI - Multi Level Dashboard", layout="wide")

# =====================================================
#  LOAD CUSTOM CSS PREMIUM
# =====================================================
with open("sabdatani.css") as f:
    st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)


# =====================================================
#  PARSER BARU (Kecamatan → Desa → Banyak Gapoktan)
# =====================================================
@st.cache_data
def load_data():
    # Baca file Excel
    df_raw = pd.read_excel("data1.xlsx", header=None)

    result = []

    # Kolom A = Kecamatan
    kecamatan = str(df_raw.iloc[0, 0]).strip()

    # Kolom B–M = Nama desa (header)
    desa_headers = df_raw.iloc[0, 1:13].tolist()

    # Proses setiap desa berdasarkan kolom
    for col_idx, desa_name in enumerate(desa_headers, start=1):

        if pd.isna(desa_name) or str(desa_name).strip() == "":
            continue

        desa_name = str(desa_name).strip()

        # Ambil seluruh gapoktan di bawah kolom desa ini
        gapoktan_col = df_raw.iloc[1:, col_idx]  # mulai dari baris kedua

        gapoktan_list = [
            str(x).strip()
            for x in gapoktan_col
            if pd.notna(x) and str(x).strip() != ""
        ]

        # Simpan data desa → semua gapoktan
        for gap in gapoktan_list:
            result.append([kecamatan, desa_name, gap])

    # Jadikan DataFrame
    df = pd.DataFrame(result, columns=["Kecamatan", "Desa", "Gapoktan"])

    return df


# Load data
df = load_data()

# =====================================================
#  TITLE
# =====================================================
st.markdown("""
<h1 class='title-main'>🌾 SABDA TANI – Dashboard Multi-Level</h1>
<h3>Kecamatan → Desa → Daftar Gapoktan</h3>
""", unsafe_allow_html=True)

# =====================================================
#  MULTI-LEVEL SELECTOR
# =====================================================

st.subheader("🔎 Drill Down Data")

# Karena hanya 1 kecamatan pada data1, tampilkan otomatis
kecamatan_name = df["Kecamatan"].unique()[0]
st.markdown(f"### 🏞 Kecamatan: **{kecamatan_name}**")

# PILIH DESA
desa_select = st.selectbox(
    "Pilih Desa",
    df["Desa"].unique()
)

# FILTER GAPOKTAN PER DESA
filtered = df[df["Desa"] == desa_select]

# =====================================================
#  Tampilkan Gapoktan
# =====================================================
st.markdown(f"""
### 🌱 Daftar Gapoktan di **{desa_select}**
Jumlah Gapoktan: **{len(filtered)}**
""")

st.table(filtered[["Gapoktan"]].reset_index(drop=True))

# =====================================================
#  KARTU PREMIUM
# =====================================================
st.markdown("### 🌿 Gapoktan (Kartu Premium)")

cols = st.columns(3)
i = 0
for gap in filtered["Gapoktan"]:
    with cols[i % 3]:
        st.markdown(
            f"""
            <div class='card'>
                <h3>{gap}</h3>
            </div>
            """,
            unsafe_allow_html=True
        )
    i += 1

# =====================================================
#  GRAFIK GAPOKTAN PER DESA
# =====================================================
st.markdown("### 📊 Grafik Jumlah Gapoktan per Desa")

desa_count = (
    df.groupby("Desa")
    .size()
    .reset_index(name="Jumlah Gapoktan")
    .sort_values("Jumlah Gapoktan", ascending=False)
)

fig = px.bar(
    desa_count,
    x="Desa",
    y="Jumlah Gapoktan",
    color="Jumlah Gapoktan",
    title="Perbandingan Jumlah Gapoktan per Desa",
    color_continuous_scale="Greens",
)

st.plotly_chart(fig, use_container_width=True)

