# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U6WD5A-bvWqPlW8_Z1xZ9QG9DkF00Q_s
"""
# ============================================
# SABDA TANI DASHBOARD – FINAL PREMIUM VERSION
# Kecamatan → Desa → Gapoktan (Clean)
# ============================================

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import plotly.express as px

# ================================
# LOAD CSS THEME
# ================================
with open("sabdatani.css") as f:
    st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

st.set_page_config(page_title="Dashboard Sabda Tani – Gapoktan", layout="wide")

# ================================
# LOAD DATA
# ================================
gapoktan_df = pd.read_excel("data1.xlsx")      # Desa → Gapoktan
kec_desa_df = pd.read_csv("poktan_clean.csv")  # Kecamatan → Desa


# ================================
# LIST KECAMATAN (ambil dari kolom pertama file data1.xlsx)
# ================================
def load_kecamatan_list(df):
    return (
        df.iloc[:, 0]          # kolom pertama = kecamatan
        .dropna()
        .astype(str)
        .str.strip()
        .drop_duplicates()
        .tolist()
    )

list_kecamatan_clean = load_kecamatan_list(gapoktan_df)



# ================================
# PARSER DESA → LIST GAPOKTAN
# ================================
def parse_gapoktan(df):
    result = {}
    for col in df.columns:
        desa = col.strip()
        items = df[col].dropna().astype(str).tolist()
        result[desa] = items
    return result

desa_gapoktan = parse_gapoktan(gapoktan_df)


# ================================
# PARSER KECAMATAN → DESA → GAPOKTAN
# ================================
def build_hierarchy(kec_desa_df, desa_gapoktan):
    hierarchy = {}

    for _, row in kec_desa_df.iterrows():
        kec = str(row["kecamatan"]).strip()
        desa = str(row["desa"]).strip()

        if kec not in hierarchy:
            hierarchy[kec] = {}

        if desa in desa_gapoktan:
            hierarchy[kec][desa] = desa_gapoktan[desa]
        else:
            hierarchy[kec][desa] = []  # jika tidak ada gapoktan

    return hierarchy

data_hierarchy = build_hierarchy(kec_desa_df, desa_gapoktan)


# ================================
# DASHBOARD HEADER
# ================================
st.markdown("""
<div class="title">
🌾 <span>Dashboard Sabda Tani – Gapoktan</span>
</div>
""", unsafe_allow_html=True)



# ================================
# KPI CARDS
# ================================
total_kec = len(data_hierarchy)
total_desa = len(desa_gapoktan)
total_gapoktan = sum(len(v) for v in desa_gapoktan.values())

col1, col2, col3 = st.columns(3)

col1.markdown(f"""
<div class="card">
<h3>Total Kecamatan</h3>
<p>{total_kec}</p>
</div>
""", unsafe_allow_html=True)

col2.markdown(f"""
<div class="card">
<h3>Total Desa</h3>
<p>{total_desa}</p>
</div>
""", unsafe_allow_html=True)

col3.markdown(f"""
<div class="card">
<h3>Total Gapoktan</h3>
<p>{total_gapoktan}</p>
</div>
""", unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

# ================================
# GRAFIK: GAPOKTAN PER KECAMATAN
# ================================
st.markdown("### 📊 Jumlah Gapoktan per Kecamatan")

df_chart = []

for kec, desa_dict in data_hierarchy.items():
    count = sum(len(g_list) for g_list in desa_dict.values())
    df_chart.append({"kecamatan": kec, "gapoktan": count})

df_chart = pd.DataFrame(df_chart)

fig = px.bar(
    df_chart,
    x="kecamatan",
    y="gapoktan",
    color="gapoktan",
    color_continuous_scale="Greens",
    title="Distribusi Gapoktan per Kecamatan"
)
st.plotly_chart(fig, use_container_width=True)

# ================================
# MENU INTERAKTIF DETAIL
# ================================
st.markdown("### 🔎 Detail Gapoktan per Kecamatan & Desa")

c1, c2 = st.columns(2)

# --- KECAMATAN dari Excel (list bersih) ---
kec_select = c1.selectbox("Pilih Kecamatan", sorted(list_kecamatan_clean))

# --- DESA mengikuti KECAMATAN ---
desa_list = list(data_hierarchy[kec_select].keys())
desa_select = c2.selectbox("Pilih Desa", desa_list)

gapoktan_list = data_hierarchy[kec_select][desa_select]

st.markdown(f"### 🌱 Daftar Gapoktan – **{desa_select}**")

if len(gapoktan_list) == 0:
    st.info("Tidak ada data gapoktan untuk desa ini.")
else:
    for g in gapoktan_list:
        st.markdown(f"- {g}")



